GET http://localhost:3001/api/v1/persons/
################################
GET http://localhost:3001/api/v1/persons/66ce37712fce9604bf81ee43
################################
GET http://localhost:3001/info
################################
POST http://localhost:3001/api/v1/persons/
Content-Type: application/json

{
  "name": "ax",
  "number": 32434324342
}
################################
DELETE http://localhost:3001/api/v1/persons/66cdfc2e06d6c213dd5086da
################################
PATCH http://localhost:3001/api/v1/persons/66cdfadeb61050f50ee482d9
Content-Type: application/json

{
  "name": "bobby",
  "number": 715110955088
}
################################
PUT http://localhost:3001/api/v1/persons/8003
Content-Type: application/json

{
  "name": "John Doe",
  "number": 388233434849183
}