GET http://localhost:3001/api/v1/notes

################################
DELETE http://localhost:3001/api/v1/notes/66cf3f0f06600be36fab7212

################################
GET http://localhost:3001/api/v1/notes/66ce14a6abbb81633caef8ac

################################
POST http://localhost:3001/api/v1/notes
Content-Type: application/json

{
  "title": "New Note",
  "content": "pasa"
}
################################
PUT http://localhost:3001/api/v1/notes/66cf3f1706600be36fab7220
Content-Type: application/json

{
  "important": false,
  "content": "que pasa tio"
}