GET http://localhost:3001/api/v1/notes

################################
DELETE http://localhost:3001/api/v1/notes/1

################################
GET http://localhost:3001/api/v1/notes/1

################################
POST http://localhost:3001/api/v1/notes
Content-Type: application/json

{
  "title": "New Note",
  "content": "This is a new note."
}
################################
PUT http://localhost:3001/api/v1/notes/1
Content-Type: application/json

{
  "important": false,
  "content": "This is an updated note."
}